version: "2"
services:
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./.docker-config/nginx/Dockerfile
  #   restart: always
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./site/web:/var/www/html/web
  
  cron:
    build:
      context: .
      dockerfile: ./.docker-config/cron/Dockerfile
    restart: always
    environment:
      MOODHWB_URL: http://web:8080
      
  web:
    build:
      context: .
      dockerfile: ./.docker-config/craft/Dockerfile
    ports:
      - 8080:8080
    env_file: .env
