version: "2"
services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker-config/nginx/Dockerfile
    restart: always
    ports:
      - 8080:80
  
  cron:
    build:
      context: .
      dockerfile: ./.docker-config/cron/Dockerfile
    restart: always
    environment:
      MOODHWB_URL: http://nginx

  php:
    build:
      context: .
      dockerfile: ./.docker-config/php/Dockerfile
    restart: always
    expose:
      - 9000
    env_file:
      - .env
