version: "2"
services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker-config/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./site/web:/var/www/html/web
  
  cron:
    build:
      context: .
      dockerfile: ./.docker-config/cron/Dockerfile
    environment:
      MOODHWB_URL: http://nginx

  php:
    build:
      context: .
      dockerfile: ./.docker-config/php/Dockerfile
    expose:
      - 9000
    user: "www-data:www-data"
    env_file:
      - ./site/.env
    volumes:
      - ./site/config:/var/www/html/config
      - ./site/templates:/var/www/html/templates
      - ./site/translations:/var/www/html/translations
      - ./site/modules:/var/www/html/modules
      - ./site/web:/var/www/html/web
      - ./site/composer.json:/var/www/html/composer.json
    environment:
      DB_DRIVER: mysql
      DB_SERVER: database
      DB_USER: craftcms
      DB_PASSWORD: craftcms
      DB_DATABASE: craftcms5
      DB_TABLE_PREFIX: craft
      SITE_URL: http://localhost
      SECURITY_KEY: asdfasdfasdfasdfasdf

  database:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
      - ./db_conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=craftcms
      - MYSQL_DATABASE=craftcms5
      - MYSQL_USER=craftcms
      - MYSQL_PASSWORD=craftcms

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8085:80
    environment:
      PMA_HOST: database
